version: '3.5'
services:

  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: akademik
      MYSQL_USER: uwais
      MYSQL_PASSWORD: 1234
    volumes:
      - /opt/data:/var/lib/mysql
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3306:3306
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      interval: 30s
      retries: 5
    networks:
      - backend

  app:
    image: 0d3ng/komputasi-awan-akademik
    container_name: akademik-app
    ports:
      - 8090:8090
    restart: always
    depends_on:
      - mysql
    command: bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /opt/app.jar"
    networks:
      - backend