version: '3.5'
services:

  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: akademik
      MYSQL_USER: uwais
      MYSQL_PASSWORD: 1234
    volumes:
      - /opt/data:/var/lib/mysql
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3306:3306
    restart: always
    networks:
      - backend

  app:
    image: 0d3ng/komputasi-awan-akademik
    container_name: akademik-app
    ports:
      - 8090:8090
    restart: always
    depends_on:
      - mysql
    command: bash -c "java -jar /opt/app.jar"
    networks:
      - backend
networks:
  backend:
    name: backend-network